name: CI/CD for GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@latest

      - name: Set up Node.js
        uses: actions/setup-node@latest
        with:
          node-version: '20'

      - name: Cache npm dependencies
        uses: actions/cache@latest
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm install

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Add Missing Babel Plugin
        run: npm install --save-dev @babel/plugin-proposal-private-property-in-object

      # Debugging steps
      - name: Debugging: List environment variables
        run: printenv

      - name: Debugging: Check Node.js version
        run: node -v

      - name: Debugging: Check npm version
        run: npm -v

      - name: Debugging: List installed npm packages
        run: npm list

      - name: Build Project
        run: npm run build

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Deploy to GitHub Pages
        run: |
          npm install -g gh-pages
          gh-pages -d build -b gh-pages -r https://x-access-token:${{ secrets.CICD_TOKEN }}@github.com/${{ github.repository }}
